version: "3"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      - POSTGRES_DB=test_application
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
  redis:
    image: redis
  celery_worker:
    image: spelswork_web
    command: celery -A spels_test_work_backend worker --concurrency=4
  celery_beat:
    image: spelswork_web
    command: celery -A spels_test_work_backend beat
  web:
    environment:
      - DJANGO_SECRET_KEY=local
    build: .
    command: python3 manage.py runserver
    volumes:
      - .:/code:Z
    ports:
      - "8000:8000"
